version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis
    environment:
      - REDIS_PASSWORD=${PASSWORD}
    expose:
      - 6379
    volumes:
      - redis-data:/data
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./:/bot

volumes:
  postgres-data:
  redis-data:
